---
# file: tasks/use-apt.yml
#
# Configure td-agent from APT repository.
#
# @see http://docs.fluentd.org/articles/install-by-deb
# @see http://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh
#
  # apt_key stops working
- name: add APT signing key for td-agent
  shell: curl https://packages.treasuredata.com/GPG-KEY-td-agent | apt-key add -

- name: add td-agent repository
  apt_repository: repo='deb http://packages.treasuredata.com/{{tdagent_major_version}}/ubuntu/focal/ focal contrib' state=present

- name: install td-agent
  apt: name=td-agent  update_cache=yes  state=present force=yes
  when: tdagent_version is not defined

- name: install td-agent
  apt: name="td-agent={{ tdagent_version }}*"  update_cache=yes  state=present force=yes
  when: tdagent_version is defined

- name: set INIT status (SysV style)
  shell: update-rc.d td-agent defaults
  when: not tdagent_use_service|bool
