---
# file: handlers/main.yml
#

- name: reload fluentd
  service: name=fluentd state=reloaded
  when: fluentd_use_service|bool

- name: restart fluentd
  service: name=fluentd state=restarted
  when: fluentd_use_service|bool

- name: stop fluentd
  service: name=fluentd state=stopped
  when: fluentd_use_service|bool
